export const randomUserMock = [
  {
    "gender": "male",
	  "title": "Mr",
	  "full_name": "Norbert Weishaupt",
	  "city": "Rhön-Grabfeld",
	  "state": "Mecklenburg-Vorpommern",
    "country": "Germany",
	  "postcode": 52640,
	  "coordinates": { "latitude": "-42.1817", "longitude": "-152.1685" },
	  "timezone": { "offset": "+9:30", "description": "Adelaide, Darwin" },
	  "email": "norbert.weishaupt@example.com",
	  "b_date": "1956-12-23T19:09:19.602Z",
	  "age": 65,
	  "phone":  "0079-8291509",
	  "picture_large": "https://randomuser.me/api/portraits/men/28.jpg",
	  "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/28.jpg",
	  "id": "FVS1379329T",
	  "favorite": "Robert Schuman",
	  "course": "English",
	  "bg_color": "#83AB42",
    "note": "hello",
  },
  {
    "gender": "male",
	  "title": "Mr",
	  "full_name": "Claude Payne",
    "city": "Skerries",
    "state": "Longford",
    "country": "Ireland",
    "postcode": 64451,
    "coordinates": { "latitude": "-81.9272", "longitude": "179.5544" },
    "timezone": { "offset": "-12:00", "description": "Eniwetok, Kwajalein" },
    "email": "claude.payne@example.com",
    "b_date": "1966-07-31T21:57:32.876Z",
    "age": 55,
    "phone": "071-558-2972",
	  "picture_large": "https://randomuser.me/api/portraits/men/40.jpg",
	  "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/40.jpg",
    "id": "PPS2340626T",
    "favorite": "Cghtgs Fgdvgd",
    "course": "Chemistry",
    "bg_color": "#6D7E52",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Curtis Mendoza",
    "city": "Bowral",
    "state": "Western Australia",
    "country": "Australia",
    "postcode": 5234,
    "coordinates": { "latitude": "-66.8661", "longitude": "-35.7288" },
    "timezone": { "offset": "+10:00",  "description": "Eastern Australia, Guam, Vladivostok", },
    "email": "curtis.mendoza@example.com",
    "b_date": "1975-04-02T02:31:00.130Z",
    "age": 46,
    "phone": "02-6397-0344",
    "picture_large": "https://randomuser.me/api/portraits/men/4.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/4.jpg",
    "id": "TFN505504341",
    "favorite": "Ftyjhdbc Rrwt",
    "course": "Math",
    "bg_color": "#3AA3D0",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Darren Wood",
    "city": "Surrey",
    "state": "Alabama",
    "country": "United States",
    "postcode": 52941,
    "coordinates": { "latitude": "79.5827", "longitude": "164.6189" },
    "timezone": { "offset": "-9:00", "description": "Alaska" },
    "email": "darren.wood@example.com",
    "b_date": "1974-11-15T10:40:20.306Z",
    "age": 47 ,
    "phone": "(720)-981-1014",
    "picture_large": "https://randomuser.me/api/portraits/men/68.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/68.jpg",
    "id":"SSN769-88-9330",
    "favorite": "Tfgdgdb Tfcvad",
    "course": "Chemistry",
    "bg_color": "#86CF1D",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Elias Tikkanen",
    "city": "Nousiainen",
    "state": "Ostrobothnia",
    "country": "Finland",
    "postcode": 67794,
    "coordinates": { "latitude": "1.4218", "longitude": "-169.0904" },
    "timezone": { "offset": "+5:30", "description": "Bombay, Calcutta, Madras, New Delhi"},
    "email": "elias.tikkanen@example.com",
    "b_date": "1985-09-28T12:59:41.244Z",
    "age": 36,
    "phone": "04-531-159",
    "picture_large": "https://randomuser.me/api/portraits/men/34.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/34.jpg",
    "id": "HETUNaNNA013undefined",
    "favorite": "Gggtrerhg Cdfwqq",
    "course": "Dancing",
    "bg_color": "#951CAD",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Ms",
    "full_name": "Tessa Möllmann",
    "city": "Hohenstein-Ernstthal",
    "state": "Bayern",
    "country": "Germany",
    "postcode": 87827,
    "coordinates": { "latitude": "61.8456", "longitude": "67.6500" },
    "timezone": { "offset": "+4:30", "description": "Kabul" },
    "email": "tessa.mollmann@example.com",
    "b_date": "1986-05-08T09:19:12.021Z",
    "age": 35,
    "phone": "0358-7950096",
    "picture_large": "https://randomuser.me/api/portraits/women/8.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/8.jpg",
    "id": "HETUNaNfrhbfgdcvzxned",
    "favorite": "Bgtrhrtrht Gryhr",
    "course": "Chess",
    "bg_color": "#0D020F",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Miss",
    "full_name": "Maxine James",
    "city": "Brisbane",
    "state": "Northern Territory",
    "country": "Australia",
    "postcode": 797,
    "coordinates": { "latitude": "-41.1464", "longitude": "142.0238" },
    "timezone": {
    "offset": "+5:00",
    "description": "Ekaterinburg, Islamabad, Karachi, Tashkent",
    },
    "email": "maxine.james@example.com",
    "b_date": "1974-08-10T01:12:04.592Z",
    "age": 47,
    "phone": "02-7976-3904",
    "picture_large": "https://randomuser.me/api/portraits/women/94.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/94.jpg",
    "id": "TFN386597027" ,
    "favorite": "Bththt Kgdgdgd",
    "course": "Biology",
    "bg_color": "#0D025F",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Mrs",
    "full_name": "Mestan Pektemek",
    "city": "İstanbul",
    "state": "Karaman",
    "country": "Turkey",
    "postcode": 81972,
    "coordinates": { "latitude": "16.6664", "longitude": "-0.4745" },
    "timezone": { "offset": "+8:00", "description": "Beijing, Perth, Singapore, Hong Kong"},
    "email": "mestan.pektemek@example.com",
    "b_date": "1975-08-20T23:05:13.239Z",
    "age": 46,
    "phone": "(038)-418-1407",
    "picture_large": "https://randomuser.me/api/portraits/women/71.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/71.jpg",
    "id": "TFN3864437027" ,
    "favorite": "Gtrtbhrfb Bvzxcsf",
    "course": "Dance",
    "bg_color": "#C949E0",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Monsieur",
    "full_name": "Viktor Legrand",
    "city": "Gy",
    "state": "Solothurn",
    "country": "Switzerland",
    "postcode": 4919,
    "coordinates": { "latitude": "-73.3324", "longitude": "-63.8552" },
    "timezone": { "offset": "+7:00", "description": "Bangkok, Hanoi, Jakarta"},
    "email": "viktor.legrand@example.com",
    "b_date": "1994-07-04T12:08:05.427Z",
    "age": 27 ,
    "phone": "077 863 38 70",
    "picture_large": "https://randomuser.me/api/portraits/men/51.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/51.jpg",
    "id": "AVS756.2023.5649.57" ,
    "favorite": "Vgegr Eqeda",
    "course": "Dance",
    "bg_color": "#BBE12D",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Deniz Yıldırım",
    "city": "Bolu",
    "state": "Ardahan",
    "country": "Turkey",
    "postcode": 12234,
    "coordinates": { "latitude": "-42.0389", "longitude": "-86.4817" },
    "timezone": {"offset": "+6:00","description": "Almaty, Dhaka, Colombo"},
    "email": "deniz.yildirim@example.com",
    "b_date": "1981-12-12T17:49:30.416Z",
    "age": 40,
    "phone": "(602)-541-0650",
    "picture_large": "https://randomuser.me/api/portraits/men/99.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/99.jpg",
    "id": "GHT56474747643" ,
    "favorite": "Bfsvss Dqwdweff",
    "course": "Physics",
    "bg_color": "#20CD96",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Ms",
    "full_name": "Matilda Aalto",
    "city": "Tornio",
    "state": "Central Ostrobothnia",
    "country": "Finland",
    "postcode": 88244,
    "coordinates": { "latitude": "79.9136", "longitude": "83.6836" },
    "timezone": {"offset": "+6:00","description": "Almaty, Dhaka, Colombo",},
    "email": "matilda.aalto@example.com",
    "b_date": "1995-09-12T20:08:25.350Z",
    "age": 26,
    "phone": "06-843-874",
    "picture_large": "https://randomuser.me/api/portraits/women/80.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/80.jpg",
    "id": "HETUNaNNA760undefined",
    "favorite": "Tfsdgdg Kfsvvs",
    "course": "Law",
    "bg_color": "#DB771E",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Miss",
    "full_name": "Lucy Walke",
    "city": "Nelson",
    "state": "Southland",
    "country": "New Zealand",
    "postcode": 82655,
    "coordinates": { "latitude": "-27.4724", "longitude": "132.5136" },
    "timezone": { "offset": "+4:30", "description": "Kabul" },
    "email": "lucy.walker@example.com",
    "b_date": "1967-07-08T22:51:02.434Z",
    "age": 54,
    "phone": "(018)-588-0617",
    "picture_large": "https://randomuser.me/api/portraits/women/6.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/6.jpg",
    "id": "HETUNaNNAffhhffdhme760undefined",
    "favorite": "Ggtrghr Vvcsvssd",
    "course": "Biology",
    "bg_color": "#EE4A74",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Antonio Gil",
    "city": "Cuenca",
    "state": "Castilla la Mancha",
    "country": "Spain",
    "postcode": 91659,
    "coordinates": { "latitude": "-71.7038", "longitude": "-10.4243" },
    "timezone": { "offset": "+2:00","description": "Kaliningrad, South Africa",},
    "email": "antonio.gil@example.com",
    "b_date": "1974-05-10T02:24:28.197Z",
    "age": 47,
    "phone": "921-757-670",
    "picture_large": "https://randomuser.me/api/portraits/men/14.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/14.jpg",
    "id": "DNI63719733-L",
    "favorite": "Hgdddfgd Trsfafa",
    "course": "Art",
    "bg_color": "#9AA931",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "August Bertheussen",
    "city": "Arendal",
    "state": "Nord-Trøndelag",
    "country": "Norway",
    "postcode": "8518",
    "coordinates": { "latitude": "25.1087", "longitude": "-0.6986" },
    "timezone": {"offset": "+11:00","description": "Magadan, Solomon Islands, New Caledonia"},
    "email": "august.bertheussen@example.com",
    "b_date": "1956-04-28T08:50:01.255Z",
    "age": 65,
    "phone": "36513745",
    "picture_large": "https://randomuser.me/api/portraits/men/87.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/87.jpg",
    "id": "FN28045612378" ,
    "favorite": "Gfsvddg Trwrwwr",
    "course": "Biology",
    "bg_color": "#D8A73C",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Miss",
    "full_name": "Lana Ottesen",
    "city": "Sand",
    "state": "Description",
    "country": "Norway",
    "postcode": "0576",
    "coordinates": { "latitude": "4.9713", "longitude": "-14.3459" },
    "timezone": { "offset": "-10:00", "description": "Hawaii" },
    "email": "lana.ottesen@example.com",
    "b_date": "1952-03-09T08:28:33.451Z",
    "age": 69,
    "phone": "76565355",
    "picture_large": "https://randomuser.me/api/portraits/women/87.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/87.jpg",
    "id": "FN09035238279",
    "favorite": "Hgdgd Kgdgdg",
    "course": "Art",
    "bg_color": "#E8B954",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Miss",
    "full_name": "Adeline Weigand",
    "city": "Fürth",
    "state": "Mecklenburg-Vorpommern",
    "country": "Germany",
    "postcode": 80819,
    "coordinates": { "latitude": "-41.5020", "longitude": "-36.1579" },
    "timezone": {"offset": "+1:00","description": "Brussels, Copenhagen, Madrid, Paris",},
    "email": "adeline.weigand@example.com",
    "b_date": "1971-06-08T09:57:13.975Z",
    "age": 50,
    "phone": "0596-1926541",
    "picture_large": "https://randomuser.me/api/portraits/women/43.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/43.jpg",
    "id": "FN090352389776279",
    "favorite": "Fgdgdg Hfsvxvxv",
    "course": "Physics",
    "bg_color": "#825F13",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Miss",
    "full_name": "Oona Kokko",
    "city": "Iisalmi",
    "state": "Central Ostrobothnia",
    "country": "Finland",
    "postcode": 71206,
    "coordinates": { "latitude": "28.3369", "longitude": "-173.9575" },
    "timezone": {"offset": "+1:00","description": "Brussels, Copenhagen, Madrid, Paris",},
    "email": "oona.kokko@example.com",
    "b_date": "1959-03-24T21:00:30.775Z",
    "age": 62,
    "phone": "07-130-008",
    "picture_large": "https://randomuser.me/api/portraits/women/93.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/93.jpg",
    "id": "HETUNaNNA402undefined",
    "favorite": "Ghyhrh Nvddvdvd",
    "course": "Biology",
    "bg_color": "#D2CDC2",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "city": "Kongsvinger",
    "state": "Sjælland",
    "country": "Denmark",
    "postcode": 65053,
    "coordinates": { "latitude": "60.3062", "longitude": "138.5907" },
    "timezone": {"offset": "-3:00","description": "Brazil, Buenos Aires, Georgetown",},
    "email": "emil.madsen@example.com",
    "b_date": "1993-12-30T02:54:32.845Z",
    "age": 28,
    "phone": "33373580",
    "picture_large": "https://randomuser.me/api/portraits/men/40.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/40.jpg",
    "id": "CPR301293-2636",
    "favorite": "Klggdb Rqeczc",
    "course": "Math",
    "bg_color": "#9AD21A",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Mario Saez",
    "city": "Gandía",
    "state": "Cataluña",
    "country": "Spain",
    "postcode": 49123,
    "coordinates": { "latitude": "-46.9749", "longitude": "-126.6882" },
    "timezone": {"offset": "-4:00","description": "Atlantic Time (Canada), Caracas, La Paz",},
    "email": "mario.saez@example.com",
    "b_date": "1985-11-01T17:08:44.642Z",
    "age": 36,
    "phone": "907-066-616",
    "picture_large": "https://randomuser.me/api/portraits/men/53.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/53.jpg",
    "id": "DNI04671126-X",
    "favorite": "Tghfhbf Vvcsfs",
    "course": "Computer Science",
    "bg_color": "#34C107",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Mrs",
    "full_name": "آدرینا صدر",
    "city": "ارومیه",
    "state": "کرمان",
    "country": "Iran",
    "postcode": 48391,
    "coordinates": { "latitude": "-5.2616", "longitude": "-95.9339" },
    "timezone": {"offset": "-7:00","description": "Mountain Time (US & Canada)",},
    "email": "adryn.sdr@example.com",
    "b_date": "1977-01-03T08:07:23.555Z",
    "age": 44,
    "phone": "008-22619690",
    "picture_large": "https://randomuser.me/api/portraits/women/49.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/49.jpg",
    "id": "DNI04534646536-X",
    "favorite": "Ffeggege Ccsvvv",
    "course": "Computer Science",
    "bg_color": "#C2C724",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Joe Mitchell" ,
    "city": "Norwalk",
    "state": "New Jersey",
    "country": "United States",
    "postcode": 83924,
    "coordinates": { "latitude": "45.4790", "longitude": "143.8132" },
    "timezone": {"offset": "+10:00","description": "Eastern Australia, Guam, Vladivostok",},
    "email": "joe.mitchell@example.com",
    "b_date": "1948-07-07T06:09:20.491Z", 
    "age": 73,
    "phone": "(210)-514-4881",
    "picture_large": "https://randomuser.me/api/portraits/men/78.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/78.jpg",
    "id": "SSN273-52-2514",
    "favorite": "Jkkde Opvsxv",
    "course": "Statistics",
    "bg_color": "#E8E9BA",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Mrs",
    "full_name": "Maeva Walker",
    "city": "Cumberland",
    "state": "Saskatchewan",
    "country": "Canada",
    "postcode": "Z6T 3E6",
    "coordinates": { "latitude": "-31.2136", "longitude": "16.8355" },
    "timezone": { "offset": "+4:00","description": "Abu Dhabi, Muscat, Baku, Tbilisi"},
    "email": "maeva.walker@example.com",
    "b_date": "1963-04-17T16:40:45.773Z",
    "age": 58,
    "phone": "636-857-3801",
    "picture_large": "https://randomuser.me/api/portraits/women/61.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/61.jpg",
    "id": "SSN26546414",
    "favorite": "Podddg Vvssfsf",
    "course": "Law",
    "bg_color": "#3F400F",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Tim Roy",
    "city": "Créteil",
    "state": "Haut-Rhin",
    "country": "France",
    "postcode": 65772,
    "coordinates": { "latitude": "-63.5272", "longitude": "115.8694" },
    "timezone": {"offset": "+5:00","description": "Ekaterinburg, Islamabad, Karachi, Tashkent",},
    "email": "tim.roy@example.com",
    "b_date": "1983-09-20T17:50:52.872Z",
    "age": 38,
    "phone": "05-70-80-69-86",
    "picture_large": "https://randomuser.me/api/portraits/men/20.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/20.jpg",
    "id": "INSEE1NNaN94113447 74",
    "favorite": "Klgddgg Bvxaqdqw",
    "course": "Computer Science",
    "bg_color": "#12B03D",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Tristan Petersen" ,
    "city": "Stenderup",
    "state": "Syddanmark",
    "country": "Denmark",
    "postcode": 88496,
    "coordinates": { "latitude": "-77.4835", "longitude": "64.8261" },
    "timezone": {"offset": "-5:00","description": "Eastern Time (US & Canada), Bogota, Lima",},
    "email": "tristan.petersen@example.com",
    "b_date": "1950-11-26T15:19:28.764Z",
    "age": 71,
    "phone": "61523239",
    "picture_large": "https://randomuser.me/api/portraits/men/97.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/97.jpg",
    "id": "CPR261150-5443",
    "favorite": "Rvxxvvx Mggerge",
    "course": "Law",
    "bg_color": "#16A8C5",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Mrs",
    "full_name": "Kristina Skjold",
    "city": "Kolnes",
    "state": "Vest-Agder",
    "country": "Norway",
    "postcode": "4085",
    "coordinates": { "latitude": "-76.9661", "longitude": "-95.2957" },
    "timezone": { "offset": "-2:00", "description": "Mid-Atlantic" },
    "email": "kristina.skjold@example.com",
    "b_date": "1972-11-21T18:04:12.259Z",
    "age": 49,
    "phone": "71350190",
    "picture_large": "https://randomuser.me/api/portraits/women/92.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/92.jpg",
    "id": "FN21117225647",
    "favorite": "Reqvvxbg Thynbvf",
    "course": "Art",
    "bg_color": "#64BACB",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "آراد زارعی", 
    "city": "اردبیل",
    "state": "کرمان",
    "country": "Iran",
    "postcode": 84902,
    "coordinates": { "latitude": "57.8145", "longitude": "-146.6983" },
    "timezone": { "offset": "+5:45", "description": "Kathmandu" },
    "email": "ard.zraay@example.com",
    "b_date": "1989-02-12T18:41:45.531Z",
    "age": 32,
    "phone": "029-39614780",
    "picture_large": "https://randomuser.me/api/portraits/men/48.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/48.jpg",
    "id": "FN21674265",
    "favorite": "Bgggh Klvxv",
    "course": "English",
    "bg_color": "#126575",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Miss",
    "full_name": "آوینا نجاتی",
    "city": "قائم‌شهر",
    "state": "مرکزی",
    "country": "Iran",
    "postcode": 21415,
    "coordinates": { "latitude": "-51.3076", "longitude": "-146.1861" },
    "timezone": {"offset": "+11:00","description": "Magadan, Solomon Islands, New Caledonia",},
    "email": "awyn.njty@example.com",
    "b_date": "1968-11-13T05:41:01.302Z",
    "age": 53,
    "phone": "049-44129055",
    "picture_large": "https://randomuser.me/api/portraits/women/19.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/19.jpg",
    "id": "FN2647585754",
    "favorite": "Tbxbv Kgfere",
    "course": "Medicine",
    "bg_color": "#68D5EA",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Ms",
    "full_name": "Ronja Marttila",
    "city": "Kotka",
    "state": "Ostrobothnia",
    "country": "Finland",
    "postcode": 52545,
    "coordinates": { "latitude": "-88.5101", "longitude": "-32.2106" },
    "timezone": {"offset": "+11:00","description": "Magadan, Solomon Islands, New Caledonia",},
    "email": "ronja.marttila@example.com",
    "b_date": "1946-02-27T02:50:54.842Z",
    "age": 75,
    "phone": "04-421-028",
    "picture_large": "https://randomuser.me/api/portraits/women/5.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/5.jpg",
    "id": "HETUNaNNA728undefined",
    "favorite": "Gvxggr Tfgsvvs",
    "course": "Law",
    "bg_color": "#A7DA1F",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Mrs",
    "full_name": "Elcke Graumans" ,
    "city": "Eemshaven",
    "state": "Groningen",
    "country": "Netherlands",
    "postcode": 79822,
    "coordinates": { "latitude": "-73.7593", "longitude": "-162.6167" },
    "timezone": { "offset": "-2:00", "description": "Mid-Atlantic" },
    "email": "elcke.graumans@example.com",
    "b_date": "1987-12-26T20:55:07.940Z",
    "age": 34,
    "phone": "(938)-352-7475",
    "picture_large": "https://randomuser.me/api/portraits/women/58.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/58.jpg",
    "id": "BSN26586375",
    "favorite": "Idgdgg Bczsae",
    "course": "Math",
    "bg_color": "#E0EAC4",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Miss",
    "full_name": "Sigrid Sviggum",
    "city": "Ramsøy",
    "state": "Hordaland",
    "country": "Norway",
    "postcode": "5904",
    "coordinates": { "latitude": "62.3170", "longitude": "102.2678" },
    "timezone": {"offset": "-5:00","description": "Eastern Time (US & Canada), Bogota, Lima",},
    "email": "sigrid.sviggum@example.com",
    "b_date": "1993-10-03T01:40:10.720Z",
    "age": 28,
    "phone": "32189027",
    "picture_large": "https://randomuser.me/api/portraits/women/3.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/3.jpg",
    "id": "FN03109315264" ,
    "favorite": "Rgtdbv Cdfwsq",
    "course": "Statistics",
    "bg_color": "#C3E16F",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Emil Møller",
    "city": "Ansager",
    "state": "Danmark",
    "country": "Denmark",
    "postcode": 49442,
    "coordinates": { "latitude": "44.9585", "longitude": "152.8104" },
    "timezone": { "offset": "-3:30", "description": "Newfoundland" },
    "email": "emil.moller@example.com",
    "b_date": "1954-07-15T07:55:58.285Z",
    "age": 67,
    "phone": "17760878",
    "picture_large": "https://randomuser.me/api/portraits/men/20.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/20.jpg",
    "id": "CPR150754-2317" ,
    "favorite": "Opgtg Gcscs",
    "course": "Art",
    "bg_color": "#11B82D",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Darrell Dunne",
    "city": "Tullow",
    "state": "Wexford",
    "country": "Ireland",
    "postcode": 39242,
    "coordinates": { "latitude": "-68.2633", "longitude": "-70.6858" },
    "timezone": {"offset": "-7:00","description": "Mountain Time (US & Canada)",},
    "email": "darrell.dunne@example.com",
    "b_date": "1997-11-21T06:35:55.528Z",
    "age": 24,
    "phone": "071-488-9968",
    "picture_large": "https://randomuser.me/api/portraits/men/36.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/36.jpg",
    "id": "PPS7847438T",
    "favorite": "Tfsfg Vsfbvc",
    "course": "Medicine",
    "bg_color": "#D4DC2D",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Jordan Vidal",
    "city": "Aubervilliers",
    "state": "Hauts-de-Seine",
    "country": "France",
    "postcode": 19716,
    "coordinates": { "latitude": "-74.1635", "longitude": "-67.0556" },
    "timezone": { "offset": "+4:00","description": "Abu Dhabi, Muscat, Baku, Tbilisi",},
    "email": "jordan.vidal@example.com",
    "b_date": "1977-03-05T13:35:14.295Z",
    "age": 44 ,
    "phone": "04-31-67-71-51",
    "picture_large": "https://randomuser.me/api/portraits/men/94.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/94.jpg",
    "id": "INSEE1NNaN34394721 96", 
    "favorite": "Qrwevb Bdzcz",
    "course": "Physics",
    "bg_color": "#0AB4A9",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "عرشيا كامياران",
    "city": "اهواز",
    "state": "گلستان",
    "country": "Iran",
    "postcode": 71779,
    "coordinates": { "latitude": "41.1604", "longitude": "82.3069" },
    "timezone": { "offset": "+5:00","description": "Ekaterinburg, Islamabad, Karachi, Tashkent",},
    "email": "aarshy.kmyrn@example.com",
    "b_date": "1965-12-08T22:45:18.878Z",
    "age": 56,
    "phone": "083-31098334",
    "picture_large": "https://randomuser.me/api/portraits/men/32.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/32.jpg",
    "id": "INSDCV2NaN35643752196", 
    "favorite": "Frvgd Qcvxzvd",
    "course": "Physics",
    "bg_color": "#5DD32E",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Esat Köylüoğlu",
    "city": "Giresun",
    "state": "Konya",
    "country": "Turkey",
    "postcode": 50870,
    "coordinates": { "latitude": "-44.0832", "longitude": "-64.5925" },
    "timezone": { "offset": "+5:45", "description": "Kathmandu" },
    "email": "esat.koyluoglu@example.com",
    "b_date": "1956-01-28T20:25:36.209Z",
    "age": 65,
    "phone": "(472)-638-0730",
    "picture_large": "https://randomuser.me/api/portraits/men/57.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/57.jpg",
    "id": "gfsd4532525",
    "favorite": "Qczfg Gthcb ",
    "course": "Law",
    "bg_color": "#B00E3C",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Madame",
    "full_name": "Anouk Simon",
    "city": "Dompierre (Vd)",
    "state": "Aargau",
    "country": "Switzerland",
    "postcode": 7118,
    "coordinates": { "latitude": "-9.6384", "longitude": "31.7436" },
    "timezone": { "offset": "-5:00","description": "Eastern Time (US & Canada), Bogota, Lima",},
    "email": "anouk.simon@example.com",
    "b_date": "1982-04-05T14:22:44.269Z",
    "age": 39,
    "phone": "078 059 73 14",
    "picture_large": "https://randomuser.me/api/portraits/women/53.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/53.jpg",
    "id": "AVS756.6671.9396.83" ,
    "favorite": "Eqcz Hrgvv",
    "course": "Statistics",
    "bg_color": "#EE537F",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Ms",
    "full_name": "Sara Velasco",
    "city": "Madrid",
    "state": "Islas Baleares",
    "country": "Spain",
    "postcode": 68699,
    "coordinates": { "latitude": "-78.4139", "longitude": "115.4609" },
    "timezone": {"offset": "0:00","description": "Western Europe Time, London, Lisbon, Casablanca",},
    "email": "sara.velasco@example.com",
    "b_date": "1980-04-17T20:07:31.899Z",
    "age": 41,
    "phone": "987-689-092",
    "picture_large": "https://randomuser.me/api/portraits/women/45.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/45.jpg",
    "id": "DNI23347090-X",
    "favorite": "Opsfd Cedfv",
    "course": "Law",
    "bg_color": "#1DC61A",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Mrs",
    "full_name": "Leah Diaz",
    "city": "Vallejo",
    "state": "Wyoming",
    "country": "United States",
    "postcode": 38797,
    "coordinates": { "latitude": "85.7862", "longitude": "-0.6726" },
    "timezone": {"offset": "+5:00","description": "Ekaterinburg, Islamabad, Karachi, Tashkent",},
    "email": "leah.diaz@example.com",
    "b_date": "1992-12-20T09:32:27.922Z",
    "age": 29,
    "phone": "(173)-797-7689",
    "picture_large": "https://randomuser.me/api/portraits/women/6.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/6.jpg",
    "id": "SSN807-33-0374",
    "favorite": "Eqcxgf Igvdgdg",
    "course": "English",
    "bg_color": "#BFE125",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Quido Van der Zalm",
    "city": "Noordeinde Gld",
    "state": "Drenthe",
    "country": "Netherlands",
    "postcode": 34404,
    "coordinates": { "latitude": "-11.1926", "longitude": "-140.8227" },
    "timezone": { "offset": "-3:30", "description": "Newfoundland" },
    "email": "quido.vanderzalm@example.com",
    "b_date":  "1961-12-02T13:05:04.807Z",
    "age": 60,
    "phone": "(144)-684-1967",
    "picture_large": "https://randomuser.me/api/portraits/men/68.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/68.jpg",
    "id": "BSN59554936",
    "favorite": "Bfere Czqaedq",
    "course": "Statistics",
    "bg_color": "#BCD83C",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Mrs",
    "full_name": "Vanessa Morgan",
    "city": "Houston",
    "state": "Florida",
    "country": "United States",
    "postcode": 69723,
    "coordinates": { "latitude": "-8.8001", "longitude": "-168.5588" },
    "timezone": { "offset": "+9:30", "description": "Adelaide, Darwin" },
    "email": "vanessa.morgan@example.com",
    "b_date": "1955-11-22T15:47:38.848Z",
    "age": 66,
    "phone": "(835)-586-6028",
    "picture_large": "https://randomuser.me/api/portraits/women/69.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/69.jpg",
    "id": "SSN375-57-5719",
    "favorite": "Fvsdf Qcad",
    "course": "Dancing",
    "bg_color": "#D6EC72",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Ms",
    "full_name": "سلطانی نژاد" ,
    "city": "نیشابور",
    "state": "همدان",
    "country": "Iran",
    "postcode": 66423,
    "coordinates": { "latitude": "7.6396", "longitude": "-26.9170" },
    "timezone": {"offset": "-8:00","description": "Pacific Time (US & Canada)",},
    "email": "awyn.sltnynjd@example.com",
    "b_date": "1994-08-26T17:01:22.484Z",
    "age": 27,
    "phone": "006-79317326",
    "picture_large": "https://randomuser.me/api/portraits/women/81.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/81.jpg",
    "id": "SSN357-57-3219",
    "favorite": "Iofds Mrfwr",
    "course": "Chess",
    "bg_color": "#1BCA65",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Oscar Dupont",
    "city": "Grenoble",
    "state": "Aveyron",
    "country": "France",
    "postcode": 27916,
    "coordinates": { "latitude": "32.9637", "longitude": "-78.6173" },
    "timezone": {"offset": "-11:00","description": "Midway Island, Samoa"},
    "email": "oscar.dupont@example.com",
    "b_date": "1951-01-16T07:15:43.883Z", "age": 70,
    "phone": "03-39-75-54-47",
    "phone": "006-79317326",
    "picture_large": "https://randomuser.me/api/portraits/men/42.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/42.jpg",
    "id": "INSEE1NNaN65034787 26",
    "favorite": "Idgbb Lwsrs",
    "course": "Physics",
    "bg_color": "#098AB4",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Ms",
    "full_name": "مهدیسمرادی",
    "city": "ارومیه",
    "state": "فارس",
    "country": "Iran",
    "postcode": 84580,
    "coordinates": { "latitude": "45.7509", "longitude": "75.8284" },
    "timezone": {"offset": "+9:00","description": "Tokyo, Seoul, Osaka, Sapporo, Yakutsk",},
    "email": "mhdys.mrdy@example.com",
    "b_date": "1952-10-04T09:02:09.900Z",
    "age": 69,
    "phone": "015-09271245",
    "picture_large": "https://randomuser.me/api/portraits/women/24.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/24.jpg",
    "id": "INSENDWN65574357 26",
    "favorite": "Idgbb Lwsrs",
    "course": "Physics",
    "bg_color": "#69BEDA",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Monsieur",
    "full_name": "Noa Bertrand",
    "city": "Reiden",
    "state": "Schwyz",
    "country": "Switzerland",
    "postcode": 9703,
    "coordinates": { "latitude": "-74.4969", "longitude": "-152.0049" },
    "timezone": {"offset": "-3:00","description": "Brazil, Buenos Aires, Georgetown",},
    "email": "noa.bertrand@example.com",
    "b_date": "1955-10-20T18:03:04.151Z",
    "age": 66,
    "phone": "078 301 62 63",
    "picture_large": "https://randomuser.me/api/portraits/men/4.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/4.jpg",
    "id": "AVS756.7424.4611.08",
    "favorite": "Tfsfg Vsfbvc",
    "course": "Medicine",
    "bg_color": "#AF7A1D",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Jerrold Kliphuis", 
    "city": "Rheezerveen",
    "state": "Noord-Holland",
    "country": "Netherlands",
    "postcode": 76283,
    "coordinates": { "latitude": "48.2285", "longitude": "-79.7590" },
    "timezone": { "offset": "+4:30", "description": "Kabul" },
    "email": "jerrold.kliphuis@example.com",
    "b_date": "1968-03-24T06:29:47.075Z",
    "age": 53,
    "phone": "(018)-382-5902",
    "picture_large": "https://randomuser.me/api/portraits/men/74.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/74.jpg",
    "id": "BSN84507586" ,
    "favorite": "Ffeggege Ccsvvv",
    "course": "Computer Science",
    "bg_color": "#99C54D",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Miss", 
    "full_name": "Beatrice Bergeron",
    "city": "Sutton",
    "state": "Alberta",
    "country": "Canada",
    "postcode": "G1J 5T2",
    "coordinates": { "latitude": "68.0346", "longitude": "165.2673" },
    "timezone": {"offset": "-4:00","description": "Atlantic Time (Canada), Caracas, La Paz",},
    "email": "beatrice.bergeron@example.com",
    "b_date": "1957-01-28T03:46:41.370Z",
    "age": 64,
    "phone": "338-732-2677",
    "picture_large": "https://randomuser.me/api/portraits/women/3.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/women/3.jpg",
    "id": "ERQ84556326" ,
    "favorite": "Ggtrghr Vvcsvssd",
    "course": "Biology",
    "bg_color": "#EE4A74",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Lucas Kristensen",
    "city": "Allinge",
    "state": "Sjælland",
    "country": "Denmark",
    "postcode": 94452,
    "coordinates": { "latitude": "-74.1864", "longitude": "23.5624" },
    "timezone": { "offset": "+9:30", "description": "Adelae, Darwin" },
    "email": "lucas.kristensen@example.com",
    "b_date": "1983-03-31T14:04:35.291Z",
    "age": 38,
    "phone": "67399596",
    "picture_large": "https://randomuser.me/api/portraits/men/3.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/3.jpg",
    "id": "CPR310383-9581" ,
    "favorite": "Gtrtbhrfb Bvzxcsf",
    "course": "Dance",
    "bg_color": "#16B298",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Eugene Kuhn",
    "city": "St. Petersburg",
    "state": "Florida",
    "country": "United States",
    "postcode": 11620,
    "coordinates": { "latitude": "41.6479", "longitude": "-79.9292" },
    "timezone": {"offset": "+4:00","description": "Abu Dhabi, Muscat, Baku, Tbilisi",},
    "email": "eugene.kuhn@example.com",
    "b_date": "1957-12-04T07:34:06.971Z",
    "age": 64,
    "phone": "(903)-380-2376",
    "picture_large": "https://randomuser.me/api/portraits/men/48.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/48.jpg",
    "id": "SSN891-26-1846",
    "favorite": "Opgtg Gcscs",
    "course": "Art",
    "bg_color": "#7386DC",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Frederikke Sørensen",
    "city": "Sønder Stenderup",
    "state": "Sjælland",
    "country": "Denmark",
    "postcode": 18668,
    "coordinates": { "latitude": "-69.4969", "longitude": "-146.2993" },
    "timezone": { "offset": "+5:45", "description": "Kathmandu" },
    "email": "frederikke.sorensen@example.com",
    "b_date": "1964-03-23T21:11:35.935Z",
    "age": 57,
    "phone": "07190090",
    "picture_large": "https://randomuser.me/api/portraits/men/28.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/28.jpg",
    "id": "CPR230364-8018" ,
    "favorite": "Tfgdgdb Tfcvad",
    "course": "Chemistry",
    "bg_color": "#4027B2",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Matteo Lecomte",
    "city": "Courbevoie",
    "state": "Charente",
    "country": "France",
    "postcode": 89507,
    "coordinates": { "latitude": "89.1833", "longitude": "-4.8202" },
    "timezone": { "offset": "+9:30", "description": "Adelaide, Darwin" },
    "email": "matteo.lecomte@example.com",
    "b_date": "1948-05-30T04:28:42.593Z",
    "age": 73,
    "phone": "02-33-67-58-40",
    "picture_large": "https://randomuser.me/api/portraits/men/57.jpg",
    "picture_thumbnail": "https://randomuser.me/api/portraits/thumb/men/57.jpg",
    "id":  "INSEE1NNaN8470722961",
    "favorite": "Idgdgg Bczsae",
    "course": "Math",
    "bg_color": "#9518A1",
    "note": "hello",
  },
  {
    "gender": "male",
    "title": "Mr",
    "full_name": "Aaron Enoksen",
    "city": "Bruflat",
    "state": "Rogaland",
    "country": "Norway",
    "postcode": "6913",
    "coordinates": { "latitude": "51.4281", "longitude": "-160.4653" },
    "timezone": { "offset": "+3:30", "description": "Tehran" },
    "email": "aaron.enoksen@example.com",
    "id": "FN19068929566",
    "favorite": "Bfsvss Dqwdweff",
    "course": "Physics",
    "bg_color": "#20CD96",
    "note": "hello",
  },
  {
    "gender": "woman",
    "title": "Mrs",
    "full_name": "Olivia Storm",
    "city": "Kragerø",
    "country": "Norway",
    "postcode": "3127",
    "coordinates": { "latitude": "57.2663", "longitude": "141.0994" },
    "timezone": { "offset": "+1:00", "description": "Brussels, Copenhagen, Madrid, Paris" },
    "b_day": "1946-06-02T09:26:02.733Z",
    "id": "FN02064618043",
    "picture_large": "https://randomuser.me/api/portraits/women/67.jpg",
    "favorite": "Tfgdgdb Tfcvad",
    "course": "Chemistry",
    "bg_color": "#86CF1D",
    "note": "old lady with a cats",
  },
];

export const additionalUsers = [


];

export let favoriteTeachers = [
  {
    "picture_large": "",
    "id": "",
    "name": "",
  }
];
